import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  private data;
  private imgUrl;
  constructor() {
    this.imgUrl="../assets/images/bb8d2.png";
    this.data = [
      {
        "user_id": 1,
        "username": "amiphuong",
        "password": "amiphuong96",
        "ten_user": "Nguyễn Mai Phương",
        "sodienthoai": "0357535712",
        "email": "nmaiphuong2015@gmail.com",
        "post":[
          {
          "id_bds": 1,
          "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
          "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
          "gia": "3 tỷ",
          "dien_tich": "250m2",
          "so_phong_ngu": "",
          "so_wc": "",
          "noi_that": "",
          "loai_tin": "bán đất",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "đông nam"
          },
          {
          "id_bds": 2,
          "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
          "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
          "gia": "5 triệu/tháng",
          "dien_tich": "100m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          },
          {
          "id_bds": 3,
          "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
          "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
          "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
          "gia": "5.7 tỷ",
          "dien_tich": "110m2",
          "so_phong_ngu": "3",
          "so_wc": "3",
          "noi_that": "đầy đ",
          "loai_tin": "bán nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "tây nam"
          },
          {
          "id_bds": 4,
          "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
          "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
          "gia": "10 triệu/tháng",
          "dien_tich": "85m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          },
          {
          "id_bds": 5,
          "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
          "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
          "gia": "3 tỷ",
          "dien_tich": "250m2",
          "so_phong_ngu": "",
          "so_wc": "",
          "noi_that": "",
          "loai_tin": "bán đất",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "đông nam"
          },
          {
          "id_bds": 6,
          "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
          "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
          "gia": "5 triệu/tháng",
          "dien_tich": "100m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          },
          {
          "id_bds": 7,
          "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
          "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
          "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
          "gia": "5.7 tỷ",
          "dien_tich": "110m2",
          "so_phong_ngu": "3",
          "so_wc": "3",
          "noi_that": "đầy đ",
          "loai_tin": "bán nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "tây nam"
          },
          {
          "id_bds": 8,
          "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
          "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
          "gia": "10 triệu/tháng",
          "dien_tich": "85m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          },
          {
          "id_bds": 9,
          "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
          "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
          "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
          "gia": "5.7 tỷ",
          "dien_tich": "110m2",
          "so_phong_ngu": "3",
          "so_wc": "3",
          "noi_that": "đầy đ",
          "loai_tin": "bán nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "tây nam"
          },
          {
          "id_bds": 10,
          "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
          "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
          "gia": "10 triệu/tháng",
          "dien_tich": "85m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          }
        ]
      },
      {
        "user_id": 2,
        "username": "phuongnguyen",
        "password": "phuongnguyen96",
        "ten_user": "Phương Nguyễn Liên",
        "sodienthoai": "0357537512",
        "email": "nmaiphuong15@gmail.com",
        "post":[
          {
          "id_bds": 11,
          "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
          "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
          "gia": "3 tỷ",
          "dien_tich": "250m2",
          "so_phong_ngu": "",
          "so_wc": "",
          "noi_that": "",
          "loai_tin": "bán đất",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "đông nam"
          },
          {
          "id_bds": 12,
          "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
          "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
          "gia": "5 triệu/tháng",
          "dien_tich": "100m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          },
          {
          "id_bds": 13,
          "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
          "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
          "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
          "gia": "5.7 tỷ",
          "dien_tich": "110m2",
          "so_phong_ngu": "3",
          "so_wc": "3",
          "noi_that": "đầy đ",
          "loai_tin": "bán nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "tây nam"
          },
          {
          "id_bds": 14,
          "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
          "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
          "gia": "10 triệu/tháng",
          "dien_tich": "85m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          },
          {
          "id_bds": 15,
          "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
          "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
          "gia": "3 tỷ",
          "dien_tich": "250m2",
          "so_phong_ngu": "",
          "so_wc": "",
          "noi_that": "",
          "loai_tin": "bán đất",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "đông nam"
          },
          {
          "id_bds": 16,
          "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
          "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
          "gia": "5 triệu/tháng",
          "dien_tich": "100m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          },
          {
          "id_bds": 17,
          "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
          "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
          "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
          "gia": "5.7 tỷ",
          "dien_tich": "110m2",
          "so_phong_ngu": "3",
          "so_wc": "3",
          "noi_that": "đầy đ",
          "loai_tin": "bán nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "tây nam"
          },
          {
          "id_bds": 18,
          "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
          "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
          "gia": "10 triệu/tháng",
          "dien_tich": "85m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          },
          {
          "id_bds": 19,
          "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
          "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
          "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
          "gia": "5.7 tỷ",
          "dien_tich": "110m2",
          "so_phong_ngu": "3",
          "so_wc": "3",
          "noi_that": "đầy đ",
          "loai_tin": "bán nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "tây nam"
          },
          {
          "id_bds": 20,
          "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
          "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
          "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
          "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
          "gia": "10 triệu/tháng",
          "dien_tich": "85m2",
          "so_phong_ngu": "3",
          "so_wc": "2",
          "noi_that": "đầy đủ",
          "loai_tin": "thuê nhà",
          "khu_vuc": "Thành phố Thái Nguyên",
          "phong_thuy": "dông bắc"
          }
        ]
      },
      {
        "user_id": 3,
     "username": "hoatran",
     "password": "abc123456",
     "ten_user": "Trần Thanh Hòa",
     "sodienthoai": "0357531234",
     "email": "nmai2015@gmail.com",
     "post":[
         {
         "id_bds": 21,
         "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
         "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
         "gia": "3 tỷ",
         "dien_tich": "250m2",
         "so_phong_ngu": "",
         "so_wc": "",
         "noi_that": "",
         "loai_tin": "bán đất",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "đông nam"
         },
         {
         "id_bds": 22,
         "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
         "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
         "gia": "5 triệu/tháng",
         "dien_tich": "100m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 23,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 24,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 25,
         "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
         "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
         "gia": "3 tỷ",
         "dien_tich": "250m2",
         "so_phong_ngu": "",
         "so_wc": "",
         "noi_that": "",
         "loai_tin": "bán đất",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "đông nam"
         },
         {
         "id_bds": 26,
         "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
         "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
         "gia": "5 triệu/tháng",
         "dien_tich": "100m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 27,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 28,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 29,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 30,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         }
       ]
      },
      {
        "user_id": 4,
     "username": "amiphuong1",
     "password": "amiphuong961",
     "ten_user": "Nguyễn Mai Phương1",
     "sodienthoai": "0357535713",
     "email": "nmaiphuong@gmail.com",
     "post":[
         {
         "id_bds": 31,
         "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
         "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
         "gia": "3 tỷ",
         "dien_tich": "250m2",
         "so_phong_ngu": "",
         "so_wc": "",
         "noi_that": "",
         "loai_tin": "bán đất",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "đông nam"
         },
         {
         "id_bds": 32,
         "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
         "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
         "gia": "5 triệu/tháng",
         "dien_tich": "100m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 33,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 34,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 35,
         "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
         "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
         "gia": "3 tỷ",
         "dien_tich": "250m2",
         "so_phong_ngu": "",
         "so_wc": "",
         "noi_that": "",
         "loai_tin": "bán đất",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "đông nam"
         },
         {
         "id_bds": 36,
         "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
         "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
         "gia": "5 triệu/tháng",
         "dien_tich": "100m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 37,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 38,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 39,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 40,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         }
       ]
      },
      {
        "user_id": 5,
     "username": "phuongnguyen1",
     "password": "phuongnguyen961",
     "ten_user": "Phương Nguyễn Liên1",
     "sodienthoai": "0357537122",
     "email": "nmaiphuong1@gmail.com",
     "post":[
         {
         "id_bds": 41,
         "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
         "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
         "gia": "3 tỷ",
         "dien_tich": "250m2",
         "so_phong_ngu": "",
         "so_wc": "",
         "noi_that": "",
         "loai_tin": "bán đất",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "đông nam"
         },
         {
         "id_bds": 42,
         "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
         "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
         "gia": "5 triệu/tháng",
         "dien_tich": "100m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 43,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 44,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 45,
         "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
         "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
         "gia": "3 tỷ",
         "dien_tich": "250m2",
         "so_phong_ngu": "",
         "so_wc": "",
         "noi_that": "",
         "loai_tin": "bán đất",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "đông nam"
         },
         {
         "id_bds": 46,
         "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
         "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
         "gia": "5 triệu/tháng",
         "dien_tich": "100m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 47,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 48,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 49,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 50,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         }
       ]
      },
      {
        "user_id": 6,
     "username": "hoatran",
     "password": "abc1234561",
     "ten_user": "Trần Thanh Hòa1",
     "sodienthoai": "0357531231",
     "email": "nmai201445@gmail.com",
     "post":[
         {
         "id_bds": 51,
         "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
         "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
         "gia": "3 tỷ",
         "dien_tich": "250m2",
         "so_phong_ngu": "",
         "so_wc": "",
         "noi_that": "",
         "loai_tin": "bán đất",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "đông nam"
         },
         {
         "id_bds": 52,
         "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
         "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
         "gia": "5 triệu/tháng",
         "dien_tich": "100m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 53,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 54,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 55,
         "ten_bds": "Bán đất phân lô, KD 915 Gia Sàng, Thái Nguyên. 250m2 chỉ 3 tỷ",
         "dia_chi": "Đường Cách Mạng Tháng Tám, Phường Gia Sàng, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "BÁN NHANH MẢNH ĐẤT GIA SÀNG. Chính chủ bán mảnh đất thuộc phường Gia Sàng, đối diện trường 915. Khu vực đang phát triển, phù hợp để xây nhà hàng, khách sạn hoặc nghỉ dưỡng. Vị trí đắc địa, đối diện trường liên cấp quốc tế 915 Gia Sàng, gần khu tái định cư mới",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/1/15/images/20190115_054633_3960696_1.jpg",
         "gia": "3 tỷ",
         "dien_tich": "250m2",
         "so_phong_ngu": "",
         "so_wc": "",
         "noi_that": "",
         "loai_tin": "bán đất",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "đông nam"
         },
         {
         "id_bds": 56,
         "ten_bds": "Cho thuê nhà 2 tầng mặt đường Thống Nhất (Gần ngã 3 bắc nam)",
         "dia_chi": "Tổ 12, Đường Thống Nhất, Phường Đồng Quang, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Cần cho thuê nhà 2 tầng mặt đường thống nhất (Gần ngã 3 bắc nam). Đã được sơn sửa đẹp, sạch sẽ, có trần thạch cao. Dãy phố có an ninh tốt, xung quanh có nhiều quán ăn sáng. Có thể kết hợp để ở và kinh doanh cafe, quán game, salon tóc...",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2019/3/17/images/20190317_084036_4123032_0.jpg",
         "gia": "5 triệu/tháng",
         "dien_tich": "100m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 57,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 58,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         },
         {
         "id_bds": 59,
         "ten_bds": "BÁN CĂN NHÀ ĐẲNG CẤP CHÂU ÂU SANG TRỌNG ĐẾN TỪNG CM HAI MẶT TIỀN",
         "dia_chi": "Phường Túc Duyên, TP Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Bán căn nhà đẳng cấp châu âu sang trọng đến từng cm hai mặt tiền diện tích 110m x 4san đầy đủ công năng cho một gia đình lý tưởng. Tất cả các thiết bị nội thất đều là hàng cao cấp để phục vụ khách vip. Một hướng tây nam và một hướng đông nam phù hợp với rất nhiều người. Nằm trong khu vực dân cư số 6 túc duyên gần khách sạn monaco nơi hội tụ của các đại gia và doanh nhân thành đạt.",
         "hinh_anh": "http://batdongsanthainguyen.net/Uploads/Products/2017/9/5/Thumb/36246/500_375_td.jpg",
         "gia": "5.7 tỷ",
         "dien_tich": "110m2",
         "so_phong_ngu": "3",
         "so_wc": "3",
         "noi_that": "đầy đ",
         "loai_tin": "bán nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "tây nam"
         },
         {
         "id_bds": 60,
         "ten_bds": "Cho thuê căn hộ chung cư Tecco Phủ Liễn",
         "dia_chi": " Đường Phủ Liễn, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên, Thái Nguyên",
         "chi_tiet": "Đặc điểm nổi bật của Tecco Tower:* Tọa lạc tại vị trí vàng ngay trung tâm thành phố * Trang thiết bị đầy đủ nội thất full phòng * Tất cả các phòng đều được thiết kế thông minh, theo phong cách Á Đông * Giao thông hoàn hảo, thuận lợi di chuyển đến các khu vực khác * An ninh 24/24, mỗi căn hộ để được 1 oto và 2 xe máy.",
         "hinh_anh": "https://alonhadat.com.vn/files/properties/2018/8/29/images/20180829_104024_3414801_0.jpg",
         "gia": "10 triệu/tháng",
         "dien_tich": "85m2",
         "so_phong_ngu": "3",
         "so_wc": "2",
         "noi_that": "đầy đủ",
         "loai_tin": "thuê nhà",
         "khu_vuc": "Thành phố Thái Nguyên",
         "phong_thuy": "dông bắc"
         }
       ]
      }
    ]
  }
  getData(){
    return this.data;
  }
  getUrl(){
    return this.imgUrl;
  }
}